entrypoint: bundle exec rails server -p $PORT -e production
env: flex
beta_settings:
  cloud_sql_instances: coloring-book-gpt:us-west2:coloring-book-gpt-prod-database
includes:
  - env_variables.yaml
